// ReSharper disable RedundantNameQualifier
namespace Willow.DeviceAutomation.InputDevices.Extensions;

internal static class KeyExtensions
{
    // ReSharper disable once RedundantNameQualifier
    public static Desktop.Robot.Key ToRobot(this Willow.DeviceAutomation.InputDevices.Enums.Key key)
    {
        return key switch
        {
            Willow.DeviceAutomation.InputDevices.Enums.Key.A => Desktop.Robot.Key.A,
            Willow.DeviceAutomation.InputDevices.Enums.Key.B => Desktop.Robot.Key.B,
            Willow.DeviceAutomation.InputDevices.Enums.Key.C => Desktop.Robot.Key.C,
            Willow.DeviceAutomation.InputDevices.Enums.Key.D => Desktop.Robot.Key.D,
            Willow.DeviceAutomation.InputDevices.Enums.Key.E => Desktop.Robot.Key.E,
            Willow.DeviceAutomation.InputDevices.Enums.Key.F => Desktop.Robot.Key.F,
            Willow.DeviceAutomation.InputDevices.Enums.Key.G => Desktop.Robot.Key.G,
            Willow.DeviceAutomation.InputDevices.Enums.Key.H => Desktop.Robot.Key.H,
            Willow.DeviceAutomation.InputDevices.Enums.Key.I => Desktop.Robot.Key.I,
            Willow.DeviceAutomation.InputDevices.Enums.Key.J => Desktop.Robot.Key.J,
            Willow.DeviceAutomation.InputDevices.Enums.Key.K => Desktop.Robot.Key.K,
            Willow.DeviceAutomation.InputDevices.Enums.Key.L => Desktop.Robot.Key.L,
            Willow.DeviceAutomation.InputDevices.Enums.Key.M => Desktop.Robot.Key.M,
            Willow.DeviceAutomation.InputDevices.Enums.Key.N => Desktop.Robot.Key.N,
            Willow.DeviceAutomation.InputDevices.Enums.Key.O => Desktop.Robot.Key.O,
            Willow.DeviceAutomation.InputDevices.Enums.Key.P => Desktop.Robot.Key.P,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Q => Desktop.Robot.Key.Q,
            Willow.DeviceAutomation.InputDevices.Enums.Key.R => Desktop.Robot.Key.R,
            Willow.DeviceAutomation.InputDevices.Enums.Key.S => Desktop.Robot.Key.S,
            Willow.DeviceAutomation.InputDevices.Enums.Key.T => Desktop.Robot.Key.T,
            Willow.DeviceAutomation.InputDevices.Enums.Key.U => Desktop.Robot.Key.U,
            Willow.DeviceAutomation.InputDevices.Enums.Key.V => Desktop.Robot.Key.V,
            Willow.DeviceAutomation.InputDevices.Enums.Key.W => Desktop.Robot.Key.W,
            Willow.DeviceAutomation.InputDevices.Enums.Key.X => Desktop.Robot.Key.X,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Y => Desktop.Robot.Key.Y,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Z => Desktop.Robot.Key.Z,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Num0 => Desktop.Robot.Key.Zero,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Num1 => Desktop.Robot.Key.One,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Num2 => Desktop.Robot.Key.Two,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Num3 => Desktop.Robot.Key.Three,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Num4 => Desktop.Robot.Key.Four,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Num5 => Desktop.Robot.Key.Five,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Num6 => Desktop.Robot.Key.Six,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Num7 => Desktop.Robot.Key.Seven,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Num8 => Desktop.Robot.Key.Eight,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Num9 => Desktop.Robot.Key.Nine,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Comma => Desktop.Robot.Key.Comma,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Colon => Desktop.Robot.Key.Colon,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Semicolon => Desktop.Robot.Key.Semicolon,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Dot => Desktop.Robot.Key.Dot,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Dollar => Desktop.Robot.Key.Dollar,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Slash => Desktop.Robot.Key.Slash,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Backslash => Desktop.Robot.Key.Backslash,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Percent => Desktop.Robot.Key.Percent,
            Willow.DeviceAutomation.InputDevices.Enums.Key.LessThan => Desktop.Robot.Key.LessThan,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Equal => Desktop.Robot.Key.Equal,
            Willow.DeviceAutomation.InputDevices.Enums.Key.GreaterThan => Desktop.Robot.Key.GreaterThan,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Quotation => Desktop.Robot.Key.QuotationMark,
            Willow.DeviceAutomation.InputDevices.Enums.Key.OpenParenthesis => Desktop.Robot.Key.OpenParenthesis,
            Willow.DeviceAutomation.InputDevices.Enums.Key.CloseParenthesis => Desktop.Robot.Key.CloseParenthesis,
            Willow.DeviceAutomation.InputDevices.Enums.Key.OpenBracket => Desktop.Robot.Key.OpenBracket,
            Willow.DeviceAutomation.InputDevices.Enums.Key.CloseBracket => Desktop.Robot.Key.CloseBracket,
            Willow.DeviceAutomation.InputDevices.Enums.Key.OpenBrace => Desktop.Robot.Key.OpenBrace,
            Willow.DeviceAutomation.InputDevices.Enums.Key.CloseBrace => Desktop.Robot.Key.CloseBrace,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Question => Desktop.Robot.Key.Interrogation,
            Willow.DeviceAutomation.InputDevices.Enums.Key.LeftCommand => Desktop.Robot.Key.Command,
            Willow.DeviceAutomation.InputDevices.Enums.Key.LeftShift => Desktop.Robot.Key.Shift,
            Willow.DeviceAutomation.InputDevices.Enums.Key.LeftOption => Desktop.Robot.Key.Option,
            Willow.DeviceAutomation.InputDevices.Enums.Key.LeftControl => Desktop.Robot.Key.Control,
            Willow.DeviceAutomation.InputDevices.Enums.Key.LeftAlt => Desktop.Robot.Key.Alt,
            Willow.DeviceAutomation.InputDevices.Enums.Key.CapsLock => Desktop.Robot.Key.CapsLock,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Enter => Desktop.Robot.Key.Enter,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Tab => Desktop.Robot.Key.Tab,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Delete => Desktop.Robot.Key.Delete,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Escape => Desktop.Robot.Key.Esc,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Insert => Desktop.Robot.Key.Insert,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Home => Desktop.Robot.Key.Home,
            Willow.DeviceAutomation.InputDevices.Enums.Key.End => Desktop.Robot.Key.End,
            Willow.DeviceAutomation.InputDevices.Enums.Key.PageUp => Desktop.Robot.Key.PageUp,
            Willow.DeviceAutomation.InputDevices.Enums.Key.PageDown => Desktop.Robot.Key.PageDown,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Backspace => Desktop.Robot.Key.Backspace,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Plus => Desktop.Robot.Key.Plus,
            Willow.DeviceAutomation.InputDevices.Enums.Key.Minus => Desktop.Robot.Key.Minus,
            Willow.DeviceAutomation.InputDevices.Enums.Key.PrintScreen => Desktop.Robot.Key.PrintScreen,
            Willow.DeviceAutomation.InputDevices.Enums.Key.ScrollLock => Desktop.Robot.Key.ScrollLock,
            Willow.DeviceAutomation.InputDevices.Enums.Key.NumLock => Desktop.Robot.Key.NumLock,
            Willow.DeviceAutomation.InputDevices.Enums.Key.PauseBreak => Desktop.Robot.Key.Pause,
            Willow.DeviceAutomation.InputDevices.Enums.Key.F1 => Desktop.Robot.Key.F1,
            Willow.DeviceAutomation.InputDevices.Enums.Key.F2 => Desktop.Robot.Key.F2,
            Willow.DeviceAutomation.InputDevices.Enums.Key.F3 => Desktop.Robot.Key.F3,
            Willow.DeviceAutomation.InputDevices.Enums.Key.F4 => Desktop.Robot.Key.F4,
            Willow.DeviceAutomation.InputDevices.Enums.Key.F5 => Desktop.Robot.Key.F5,
            Willow.DeviceAutomation.InputDevices.Enums.Key.F6 => Desktop.Robot.Key.F6,
            Willow.DeviceAutomation.InputDevices.Enums.Key.F7 => Desktop.Robot.Key.F7,
            Willow.DeviceAutomation.InputDevices.Enums.Key.F8 => Desktop.Robot.Key.F8,
            Willow.DeviceAutomation.InputDevices.Enums.Key.F9 => Desktop.Robot.Key.F9,
            Willow.DeviceAutomation.InputDevices.Enums.Key.F10 => Desktop.Robot.Key.F10,
            Willow.DeviceAutomation.InputDevices.Enums.Key.F11 => Desktop.Robot.Key.F11,
            Willow.DeviceAutomation.InputDevices.Enums.Key.F12 => Desktop.Robot.Key.F12,
            Willow.DeviceAutomation.InputDevices.Enums.Key.LeftArrow => Desktop.Robot.Key.Left,
            Willow.DeviceAutomation.InputDevices.Enums.Key.UpArrow => Desktop.Robot.Key.Up,
            Willow.DeviceAutomation.InputDevices.Enums.Key.RightArrow => Desktop.Robot.Key.Right,
            Willow.DeviceAutomation.InputDevices.Enums.Key.DownArrow => Desktop.Robot.Key.Down,
            Willow.DeviceAutomation.InputDevices.Enums.Key.None => throw new InvalidOperationException("None key was pressed")
        };
    }
}